import { AkunItem } from "@/types/akun"

export const MOCK_AKUN_DATA: AkunItem[] = [
  { kode: "5", nama: "Belanja", level: 1, parent: null, b: false, r: false, h: false, t: false },
  { kode: "5.1", nama: "Belanja Operasi", level: 2, parent: "5", b: false, r: false, h: false, t: false },
  { kode: "5.1.01", nama: "Belanja Pegawai", level: 3, parent: "5.1", b: false, r: false, h: false, t: false },
  { kode: "5.1.02", nama: "Belanja Barang dan Jasa", level: 3, parent: "5.1", b: true, r: true, h: false, t: true },
  { kode: "5.1.02.01", nama: "Belanja Barang", level: 4, parent: "5.1.02", b: true, r: true, h: false, t: true },
  { kode: "5.1.02.01.01", nama: "Belanja Barang Pakai Habis", level: 5, parent: "5.1.02.01", b: true, r: true, h: false, t: true },
  { kode: "5.1.02.01.01.0024", nama: "Belanja Alat/Bahan untuk Kegiatan Kantor-Alat Tulis Kantor", level: 6, parent: "5.1.02.01.01", b: true, r: true, h: false, t: true },
  { kode: "5.1.02.01.01.0036", nama: "Belanja Bahan Obat-Obatan & Vaksin", level: 6, parent: "5.1.02.01.01", b: true, r: true, h: false, t: true },
  { kode: "5.1.02.02", nama: "Belanja Jasa", level: 4, parent: "5.1.02", b: true, r: true, h: false, t: false },
  { kode: "5.1.02.02.01", nama: "Belanja Jasa Kantor", level: 5, parent: "5.1.02.02", b: true, r: true, h: false, t: false },
  { kode: "5.1.02.02.01.0026", nama: "Belanja Jasa Konsultansi Penataan Aset Daerah", level: 6, parent: "5.1.02.02.01", b: true, r: true, h: false, t: false },
  { kode: "5.1.02.03", nama: "Belanja Pemeliharaan", level: 4, parent: "5.1.02", b: true, r: false, h: true, t: true },
  { kode: "5.1.02.03.01", nama: "Belanja Pemeliharaan Peralatan dan Mesin", level: 5, parent: "5.1.02.03", b: true, r: false, h: true, t: true },
  { kode: "5.1.02.03.02", nama: "Belanja Pemeliharaan Gedung dan Bangunan", level: 5, parent: "5.1.02.03", b: true, r: false, h: true, t: true },
  { kode: "5.2", nama: "Belanja Modal", level: 2, parent: "5", b: true, r: true, h: false, t: false },
  { kode: "5.2.01", nama: "Belanja Modal Tanah", level: 3, parent: "5.2", b: true, r: true, h: false, t: false },
  { kode: "5.2.01.01", nama: "Belanja Modal Tanah Persil", level: 4, parent: "5.2.01", b: true, r: true, h: false, t: false },
  { kode: "5.2.01.01.01.0001", nama: "Pembelian Tanah Bangunan Gedung", level: 6, parent: "5.2.01.01", b: true, r: true, h: false, t: false },
  { kode: "5.2.02", nama: "Belanja Modal Peralatan dan Mesin", level: 3, parent: "5.2", b: true, r: true, h: true, t: true },
  { kode: "5.2.02.03.01.0008", nama: "Belanja Modal Mesin Pengemas Otomatis Vacuum Sealer", level: 6, parent: "5.2.02", b: true, r: true, h: false, t: true },
  { kode: "5.2.02.05.01.0005", nama: "Belanja Modal Komputer Server Rackmount", level: 6, parent: "5.2.02", b: true, r: true, h: false, t: true },
  { kode: "5.2.02.05.02.0001", nama: "Belanja Modal Meubel Meja dan Kursi Siswa", level: 6, parent: "5.2.02", b: true, r: true, h: false, t: true },
  { kode: "5.2.02.08.01.0002", nama: "Belanja Modal Alat Kedokteran dan Diagnostik", level: 6, parent: "5.2.02", b: true, r: true, h: false, t: true },
  { kode: "5.2.03", nama: "Belanja Modal Gedung dan Bangunan", level: 3, parent: "5.2", b: true, r: true, h: true, t: false },
  { kode: "5.2.03.01.01.0001", nama: "Belanja Modal Bangunan Gedung Kantor", level: 6, parent: "5.2.03", b: true, r: true, h: true, t: false },
  { kode: "5.2.04", nama: "Belanja Modal Jalan, Jaringan, dan Irigasi", level: 3, parent: "5.2", b: true, r: true, h: true, t: true },
  { kode: "5.2.04.01.01.0001", nama: "Belanja Modal Jalan Kabupaten/Kota", level: 6, parent: "5.2.04", b: true, r: true, h: true, t: true },
  { kode: "5.2.04.02.01.0001", nama: "Belanja Modal Jembatan pada Jalan Kabupaten/Kota", level: 6, parent: "5.2.04", b: true, r: true, h: true, t: true },
]
