import { RkbmdPengadaanItem, RkbmdPemeliharaanItem } from "@/types/rkbmd"

export const INITIAL_RKBMD_PENGADAAN: RkbmdPengadaanItem[] = [
  {
    id_pengadaan: 1001,
    kode_skpd: "1.03.0.00.0.00.01.0000",
    nama_skpd: "Dinas Pekerjaan Umum, Perumahan dan Kawasan Permukiman",
    kode_sub_skpd: "1.03.0.00.0.00.01.0000",
    nama_sub_skpd: "Dinas Pekerjaan Umum, Perumahan dan Kawasan Permukiman",
    kode_program: "1.03.02",
    nama_program: "Program Penyelenggaraan Jalan",
    kode_giat: "1.03.02.1.01",
    nama_giat_nama_giat: "Penyelenggaraan Jalan Kabupaten/Kota",
    kode_sub_giat: "1.03.02.1.01.0003",
    nama_sub_giat_nama_sub_giat: "Rekonstruksi Jalan Ruas Godean - Seyegan",
    kode_fikasi: "1.3.2.01.01",
    nama_barang: "Komputer Server Rackmount 2U",
    jumlah_barang: 3,
    satuan: "Unit",
    jumlah_maksimum: 5,
    cara_pemenuhan: "Pembelian Langsung / ePurchasing",
    keterangan: "Kebutuhan server pusat data jalan & jembatan",
    nm_status: "Disetujui Penelaah",
    periode: 2026,
    created_at: "2026-02-10T08:00:00.000Z",
  },
  {
    id_pengadaan: 1002,
    kode_skpd: "1.02.0.00.0.00.01.0000",
    nama_skpd: "Dinas Kesehatan",
    kode_sub_skpd: "1.02.0.00.0.00.01.0000",
    nama_sub_skpd: "Dinas Kesehatan",
    kode_program: "1.02.03",
    nama_program: "Program Sediaan Farmasi dan Alat Kesehatan",
    kode_giat: "1.02.03.1.02",
    nama_giat_nama_giat: "Pengadaan Alat Kesehatan",
    kode_sub_giat: "1.02.03.1.02.0001",
    nama_sub_giat_nama_sub_giat: "Pengadaan USG 4 Dimensi dan Monitor Bedside RSUD",
    kode_fikasi: "1.3.2.08.02",
    nama_barang: "Alat USG 4D Obstetri Digital",
    jumlah_barang: 2,
    satuan: "Unit",
    jumlah_maksimum: 2,
    cara_pemenuhan: "Pembelian / eKatalog",
    keterangan: "Penggantian unit lama rusak berat di RSUD",
    nm_status: "Disetujui Penelaah",
    periode: 2026,
    created_at: "2026-02-12T09:30:00.000Z",
  },
  {
    id_pengadaan: 1003,
    kode_skpd: "1.01.0.00.0.00.01.0000",
    nama_skpd: "Dinas Pendidikan",
    kode_sub_skpd: "1.01.0.00.0.00.01.0000",
    nama_sub_skpd: "Dinas Pendidikan",
    kode_program: "1.01.02",
    nama_program: "Program Pengelolaan Pendidikan Dasar",
    kode_giat: "1.01.02.1.01",
    nama_giat_nama_giat: "Pengelolaan Pendidikan Sekolah Dasar",
    kode_sub_giat: "1.01.02.1.01.0003",
    nama_sub_giat_nama_sub_giat: "Penyediaan Sarana Prasarana dan Meubilair SD Negeri",
    kode_fikasi: "1.3.2.05.02",
    nama_barang: "Set Meja Kursi Siswa Kayu Jati",
    jumlah_barang: 250,
    satuan: "Set",
    jumlah_maksimum: 300,
    cara_pemenuhan: "Pembelian",
    keterangan: "Pengadaan meubilair SD Negeri 1 & SD Negeri 2",
    nm_status: "Dalam Proses Review",
    periode: 2026,
    created_at: "2026-02-14T11:00:00.000Z",
  },
  {
    id_pengadaan: 1004,
    kode_skpd: "2.16.0.00.0.00.01.0000",
    nama_skpd: "Dinas Komunikasi dan Informatika",
    kode_sub_skpd: "2.16.0.00.0.00.01.0000",
    nama_sub_skpd: "Dinas Komunikasi dan Informatika",
    kode_program: "2.16.02",
    nama_program: "Program Aplikasi Informatika dan E-Government",
    kode_giat: "2.16.02.1.01",
    nama_giat_nama_giat: "Pengelolaan Pusat Data dan Infrastruktur SPBE",
    kode_sub_giat: "2.16.02.1.01.0001",
    nama_sub_giat_nama_sub_giat: "Pengembangan Infrastruktur Jaringan & Server Data Center",
    kode_fikasi: "1.3.2.05.01",
    nama_barang: "SAN Storage System 120TB",
    jumlah_barang: 1,
    satuan: "Unit",
    jumlah_maksimum: 1,
    cara_pemenuhan: "Pembelian / eKatalog",
    keterangan: "Penambahan kapasitas data center SPBE",
    nm_status: "Disetujui Penelaah",
    periode: 2026,
    created_at: "2026-02-16T14:15:00.000Z",
  },
]

export const INITIAL_RKBMD_PEMELIHARAAN: RkbmdPemeliharaanItem[] = [
  {
    id_pemeliharaan: 2001,
    kode_skpd: "1.03.0.00.0.00.01.0000",
    nama_skpd: "Dinas Pekerjaan Umum, Perumahan dan Kawasan Permukiman",
    kode_sub_skpd: "1.03.0.00.0.00.01.0000",
    nama_sub_skpd: "Dinas Pekerjaan Umum, Perumahan dan Kawasan Permukiman",
    kode_program: "1.03.02",
    nama_program: "Program Penyelenggaraan Jalan",
    kode_kegiatan: "1.03.02.1.01",
    nama_giat_nama_giat: "Penyelenggaraan Jalan Kabupaten/Kota",
    kode_sub_kegiatan: "1.03.02.1.01.0004",
    nama_sub_giat_nama_sub_giat: "Rehabilitasi Jembatan Kali Bedog Ruas Mlati",
    kode_fikasi: "1.3.3.01.02",
    nama_barang: "Jembatan Beton Ruas Mlati",
    jumlah_barang: 1,
    satuan: "Unit",
    kondisi_b: 0,
    kondisi_rr: 1,
    kondisi_rb: 0,
    nama_pemeliharaan: "Pemeliharaan Rehabilitasi Gelagar & Expansion Joint Jembatan",
    jumlah_pemeliharaan: 1,
    satuan_pemeliharaan: "Paket",
    keterangan: "Perbaikan konstruksi penopang karena erosi",
    nm_status: "Disetujui Penelaah",
    periode: 2026,
    created_at: "2026-02-10T10:00:00.000Z",
  },
  {
    id_pemeliharaan: 2002,
    kode_skpd: "1.02.0.00.0.00.01.0000",
    nama_skpd: "Dinas Kesehatan",
    kode_sub_skpd: "1.02.0.00.0.00.01.0000",
    nama_sub_skpd: "Dinas Kesehatan",
    kode_program: "1.02.03",
    nama_program: "Program Sediaan Farmasi dan Alat Kesehatan",
    kode_kegiatan: "1.02.03.1.01",
    nama_giat_nama_giat: "Pengadaan Sediaan Farmasi dan BMHP Puskesmas",
    kode_sub_kegiatan: "1.02.03.1.01.0002",
    nama_sub_giat_nama_sub_giat: "Pengadaan Obat Esensial dan Vaksin 25 Puskesmas",
    kode_fikasi: "1.3.2.02.01",
    nama_barang: "Ambulance Transport Puskesmas",
    jumlah_barang: 5,
    satuan: "Unit",
    kondisi_b: 3,
    kondisi_rr: 2,
    kondisi_rb: 0,
    nama_pemeliharaan: "Pemeliharaan Rutin Service Berkala & Ganti Ban Mobil Ambulance",
    jumlah_pemeliharaan: 5,
    satuan_pemeliharaan: "Unit",
    keterangan: "Pemeliharaan berkala armada puskesmas",
    nm_status: "Disetujui Penelaah",
    periode: 2026,
    created_at: "2026-02-12T11:20:00.000Z",
  },
  {
    id_pemeliharaan: 2003,
    kode_skpd: "1.01.0.00.0.00.01.0000",
    nama_skpd: "Dinas Pendidikan",
    kode_sub_skpd: "1.01.0.00.0.00.01.0000",
    nama_sub_skpd: "Dinas Pendidikan",
    kode_program: "1.01.02",
    nama_program: "Program Pengelolaan Pendidikan Dasar",
    kode_kegiatan: "1.01.02.1.01",
    nama_giat_nama_giat: "Pengelolaan Pendidikan Sekolah Dasar",
    kode_sub_kegiatan: "1.01.02.1.01.0003",
    nama_sub_giat_nama_sub_giat: "Penyediaan Sarana Prasarana dan Meubilair SD Negeri",
    kode_fikasi: "1.3.1.01.01",
    nama_barang: "Gedung Ruang Kelas SD Negeri 1 Sleman",
    jumlah_barang: 12,
    satuan: "Ruang",
    kondisi_b: 8,
    kondisi_rr: 4,
    kondisi_rb: 0,
    nama_pemeliharaan: "Pemeliharaan Rehab Atap & Pengecatan Dinding Kelas",
    jumlah_pemeliharaan: 4,
    satuan_pemeliharaan: "Ruang",
    keterangan: "Rehab ringan bocor atap dan atap bocor",
    nm_status: "Dalam Proses Review",
    periode: 2026,
    created_at: "2026-02-15T09:45:00.000Z",
  },
]
